# Generated by Django 5.0.3 on 2024-03-12 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truckpartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=50)),
                ('t_email', models.EmailField(max_length=50, unique=True)),
                ('t_contact', models.CharField(max_length=11)),
                ('t_password', models.CharField(max_length=50)),
                ('t_rcnumber', models.CharField(max_length=10)),
                ('t_aadharcard_details', models.CharField(max_length=12, unique=True)),
                ('t_pancard_details', models.CharField(max_length=10, unique=True)),
                ('t_drivinglicence_details', models.CharField(max_length=15, unique=True)),
                ('t_picture', models.ImageField(default='profile/default-picture.png', upload_to='profile/')),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.booking')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
