# Generated by Django 5.0.2 on 2024-03-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truckpartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=50)),
                ('t_email', models.EmailField(max_length=50, unique=True)),
                ('t_contact', models.CharField(max_length=50)),
                ('t_password', models.CharField(max_length=50)),
                ('t_rcnumber', models.CharField(max_length=50)),
                ('t_aadharcard_details', models.CharField(max_length=50, unique=True)),
                ('t_pancard_details', models.CharField(max_length=50, unique=True)),
                ('t_drivinglicence_details', models.CharField(max_length=50, unique=True)),
                ('t_picture', models.ImageField(default='profile/default-picture.png', upload_to='profile/')),
            ],
        ),
    ]
