# Generated by Django 5.0.2 on 2024-03-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckpartner',
            name='t_aadharcard_details',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='truckpartner',
            name='t_drivinglicence_details',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='truckpartner',
            name='t_pancard_details',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='truckpartner',
            name='t_rcnumber',
            field=models.CharField(max_length=10),
        ),
    ]
