# Generated by Django 5.0.3 on 2024-03-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckpartner',
            name='t_packagetype',
            field=models.CharField(default='silver', max_length=50),
        ),
    ]
