# Generated by Django 5.0.3 on 2024-03-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0002_truckpartner_t_packagetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckpartner',
            name='t_packageprice',
            field=models.PositiveIntegerField(max_length='20', null=True),
        ),
    ]
