# Generated by Django 5.0.3 on 2024-03-13 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0002_package'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Package',
        ),
    ]
