# Generated by Django 5.0.2 on 2024-03-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0002_alter_truckpartner_t_aadharcard_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckpartner',
            name='t_contact',
            field=models.CharField(max_length=11),
        ),
    ]
