# Generated by Django 5.0.3 on 2024-03-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0003_truckpartner_t_packageprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckpartner',
            name='t_packageprice',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
