# Generated by Django 5.0.3 on 2024-03-13 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0004_package'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Package',
            new_name='Packages',
        ),
        migrations.RenameField(
            model_name='packages',
            old_name='package_name',
            new_name='packages_name',
        ),
    ]
