# Generated by Django 5.0.3 on 2024-03-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0005_rename_package_packages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
