# Generated by Django 5.0.3 on 2024-03-13 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0006_alter_packages_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='truck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp2.truckpartner'),
        ),
    ]
