# Generated by Django 5.0.2 on 2024-03-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='movefrom',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='moveto',
            field=models.TextField(),
        ),
    ]
